name: paden
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+3

environment:
  #sdk: ">=3.0.0 <4.0.0"
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  carousel_slider: ^5.1.1
  cloud_functions: ^5.6.0
  cloud_functions_platform_interface: ^5.8.0
  cloud_functions_web: ^4.11.3
  collection: 1.19.1
  csslib: ^1.0.2
  dropdown_button2: 2.3.9
  easy_debounce: ^2.0.3
  equatable: ^2.0.7
  file_picker: ^10.2.0
  firebase_analytics: ^11.5.1
  firebase_analytics_platform_interface: ^4.4.1
  firebase_analytics_web: ^0.5.10+14
  firebase_core: ^3.15.0
  firebase_core_platform_interface: ^6.0.0
  firebase_core_web: ^2.24.0
  firebase_performance: ^0.10.1+8
  firebase_performance_platform_interface: ^0.1.5+8
  firebase_performance_web: ^0.1.7+14
  flutter_animate: ^4.5.2
  flutter_cache_manager: 3.4.1
  flutter_native_splash: ^2.4.6
  flutter_plugin_android_lifecycle: ^2.0.28
  flutter_rating_bar: 4.0.1
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.8.0
  from_css_color: 2.0.0
  geolocator: ^14.0.2
  go_router: ^10.1.2
  google_fonts: ^6.2.1
  google_maps: ^8.1.1
  google_maps_flutter: ^2.6.0
  google_maps_flutter_android: ^2.16.2
  google_maps_flutter_ios: ^2.15.4
  google_maps_flutter_platform_interface: ^2.12.1
  google_maps_flutter_web: ^0.5.12+2
  html: ^0.15.6
  http: 1.2.2
  image_picker: 1.1.2
  image_picker_android: ^0.8.12+23
  image_picker_for_web: ^3.0.6
  image_picker_ios: ^0.8.12+2
  image_picker_linux: ^0.2.1+2
  image_picker_macos: ^0.2.1+2
  image_picker_platform_interface: ^2.10.1
  image_picker_windows: 0.2.1+1
  internet_connection_checker_plus: ^2.5.1
  intl: ^0.20.2
  json_path: ^0.7.6
  mime_type: ^1.0.1
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  path_provider_android: ^2.2.17
  path_provider_foundation: ^2.4.1
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: 2.3.0
  photo_view: 0.15.0
  plugin_platform_interface: 2.1.8
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  shared_preferences_android: ^2.4.10
  shared_preferences_foundation: ^2.5.4
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: ^2.4.3
  shared_preferences_windows: 2.4.1
  smooth_page_indicator: ^1.2.1
  sqflite: ^2.4.2
  sqflite_common: ^2.5.5
  timeago: ^3.7.1
  universal_io: 2.2.2
  url_launcher: ^6.3.1
  url_launcher_android: ^6.3.16
  url_launcher_ios: ^6.3.3
  url_launcher_linux: ^3.2.1
  url_launcher_macos: ^3.2.2
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: ^2.4.1
  url_launcher_windows: ^3.1.4
  video_player: ^2.10.0
  video_player_android: ^2.8.7
  video_player_avfoundation: ^2.7.2
  video_player_platform_interface: ^6.4.0
  video_player_web: ^2.3.5
  xml: 6.5.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dependency_overrides:
  http: 1.2.2
  uuid: ^4.0.0
  win32: 5.5.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  image: ^4.5.4
  lints: ^6.0.0
  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

